name: eventsource
description: A client and server implementation of Server-Sent Events.
version: 0.1.0+2
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-eventsource

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: 0.11.3+17
  logging: 0.11.3+2
  #sync: 0.1.0+1

dev_dependencies:
  test: 1.3.0
